import { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.scss'

const inter = Inter({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	display: 'swap',
	style: 'normal'
})

export const metadata: Metadata = {
	title: 'Instelloo',
	description: 'Generated by create next app',
	applicationName: 'Instelloo',
	authors: [{ name: 'DevBoys group' }],
	category: 'Social',
	keywords: ['social', 'instagram clone', 'nextjs'],
	openGraph: {
		type: 'website',
		title: 'Instelloo',
		description: 'this is instagram clone name instelloo',
		siteName: 'Instelloo'
	},
	viewport: { width: 'width=device-width', initialScale: 1 }
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	)
}
